// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "NativeGameplayTags.h"

// Movement.State
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GTag_Movement_State_Walk)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GTag_Movement_State_Run)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GTag_Movement_State_Sprint)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GTag_Movement_State_Crouch)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GTag_Movement_State_Fall)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GTag_Movement_State_Aim)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GTag_Movement_State_Dodge)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GTag_Movement_State_UseItem)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GTag_Movement_State_Jump)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(GTag_Movement_State_Pivot)